# Architecture comes from actual target properties, including FILE_SET headers.
# Normalize namespaced aliases and static PRIVATE LINK_ONLY edges before traversal.
function(football_direct_links tgt out_var)
  set(_links)
  foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(_values ${tgt} ${_prop})
    if(_values)
      foreach(_value IN LISTS _values)
        # CMake wraps cross-directory link edits in directory-id lookup markers.
        if(_value MATCHES "^::@($|\\([^)]+\\)$)")
          continue()
        endif()
        string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" _value "${_value}")
        if(_value MATCHES "^\\$<LINK_LIBRARY:[^,]+,(.*)>$")
          string(REPLACE "," ";" _candidates "${CMAKE_MATCH_1}")
        else()
          set(_candidates ${_value})
        endif()
        foreach(_candidate IN LISTS _candidates)
          if(TARGET ${_candidate})
            get_target_property(_canonical ${_candidate} ALIASED_TARGET)
            if(_canonical)
              set(_candidate ${_canonical})
            endif()
            list(APPEND _links ${_candidate})
          elseif(_candidate MATCHES "\\$<")
            message(FATAL_ERROR "Architecture validation cannot interpret link edge: ${tgt} -> ${_value}")
          else()
            # Raw libraries/flags must also be admitted explicitly by the policy.
            list(APPEND _links "${_candidate}")
          endif()
        endforeach()
      endforeach()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _links)
  set(${out_var} ${_links} PARENT_SCOPE)
endfunction()

function(football_link_closure tgt out_var)
  set(_closure ${tgt})
  set(_queue ${tgt})
  while(_queue)
    list(POP_FRONT _queue _current)
    if(TARGET ${_current})
      football_direct_links(${_current} _links)
    else()
      set(_links)
    endif()
    foreach(_link IN LISTS _links)
      if(NOT _link IN_LIST _closure)
        list(APPEND _closure ${_link})
        list(APPEND _queue ${_link})
      endif()
    endforeach()
  endwhile()
  set(${out_var} ${_closure} PARENT_SCOPE)
endfunction()

function(football_owned_files tgt out_var)
  get_target_property(_dir ${tgt} SOURCE_DIR)
  set(_files)
  foreach(_prop SOURCES INTERFACE_SOURCES)
    get_target_property(_values ${tgt} ${_prop})
    if(_values)
      list(APPEND _files ${_values})
    endif()
  endforeach()
  foreach(_prop HEADER_SETS INTERFACE_HEADER_SETS)
    get_target_property(_sets ${tgt} ${_prop})
    if(_sets)
      foreach(_set IN LISTS _sets)
        if(_set STREQUAL "HEADERS")
          get_target_property(_headers ${tgt} HEADER_SET)
        else()
          get_target_property(_headers ${tgt} HEADER_SET_${_set})
        endif()
        list(APPEND _files ${_headers})
      endforeach()
    endif()
  endforeach()
  set(_owned)
  foreach(_file IN LISTS _files)
    string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" _file "${_file}")
    if(_file MATCHES "\\$<")
      message(FATAL_ERROR "Architecture validation cannot interpret source: ${tgt} -> ${_file}")
    endif()
    get_filename_component(_absolute "${_file}" ABSOLUTE BASE_DIR "${_dir}")
    file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}/src" "${_absolute}")
    list(APPEND _owned ${_relative})
  endforeach()
  list(REMOVE_DUPLICATES _owned)
  set(${out_var} ${_owned} PARENT_SCOPE)
endfunction()

# Discover module targets recursively, including any new implementation targets.
function(football_directory_targets dir out_var)
  get_property(_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(_children DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
  foreach(_child IN LISTS _children)
    football_directory_targets("${_child}" _nested)
    list(APPEND _targets ${_nested})
  endforeach()
  set(${out_var} ${_targets} PARENT_SCOPE)
endfunction()

# Validate actual source/header metadata; a module cannot compile another module
# directly to bypass its link policy. FILE_SET headers count as owned files too.
function(football_validate_target_sources)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "TARGET;ROOT" "FILES;EXCLUDE_ROOTS")
  if(NOT ARG_TARGET OR NOT ARG_ROOT OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "football_validate_target_sources requires TARGET and ROOT")
  endif()
  file(REAL_PATH "${ARG_ROOT}" _root)
  football_owned_files(${ARG_TARGET} _files)
  foreach(_file IN LISTS _files)
    set(_absolute "${PROJECT_SOURCE_DIR}/src/${_file}")
    if(NOT EXISTS "${_absolute}" OR IS_DIRECTORY "${_absolute}")
      message(FATAL_ERROR "${ARG_TARGET} owns missing source: ${_file}")
    endif()
    file(REAL_PATH "${_absolute}" _absolute)
    cmake_path(IS_PREFIX _root "${_absolute}" NORMALIZE _inside)
    if(NOT _inside)
      message(FATAL_ERROR "${ARG_TARGET} owns foreign source: ${_file} (root: ${_root})")
    endif()
    if(ARG_FILES AND NOT _file IN_LIST ARG_FILES)
      message(FATAL_ERROR "${ARG_TARGET} owns unexpected source: ${_file}")
    endif()
    foreach(_excluded IN LISTS ARG_EXCLUDE_ROOTS)
      file(REAL_PATH "${_excluded}" _excluded_root)
      cmake_path(IS_PREFIX _excluded_root "${_absolute}" NORMALIZE _inside_excluded)
      if(_inside_excluded)
        message(FATAL_ERROR "${ARG_TARGET} owns foreign source: ${_file}")
      endif()
    endforeach()
  endforeach()
endfunction()

function(football_validate_target_dependencies tgt)
  set(_allowed ${tgt} ${ARGN})
  football_link_closure(${tgt} _closure)
  foreach(_dependency IN LISTS _closure)
    if(NOT _dependency IN_LIST _allowed)
      message(FATAL_ERROR "Forbidden architecture dependency: ${tgt} -> ${_dependency}")
    endif()
  endforeach()
endfunction()

# The permanent architecture is a closed DAG, validated in every build mode.
# These are transitive allow-lists, not a second recipe for target_link_libraries.
function(football_validate_architecture)
  set(_base football_model football_foundation)
  set(_values ${_base} football_sim_contracts)
  set(_runtime ${_values} football_animation football_support football_sim)
  set(_policy ${_values} football_ai_contracts football_ai)
  set(_offline football_legacy_anim football_animation football_support football_foundation)

  set(_root_football_model model)
  set(_root_football_foundation foundation)
  set(_root_football_support support)
  set(_root_football_sim_contracts sim)
  set(_root_football_animation sim/animation)
  set(_root_football_sim sim)
  set(_root_football_ai_contracts ai)
  set(_root_football_ai ai)
  set(_root_football_app_support app)
  set(_root_football_app app)
  set(_root_game .)
  set(_root_football_legacy_anim ../tools/animBaker)
  set(_root_football_anim_baking ../tools/animBaker)
  set(_root_football_anim_baker ../tools/animBaker)

  set(_deps_football_model)
  set(_deps_football_foundation)
  set(_deps_football_support football_foundation)
  set(_deps_football_sim_contracts ${_base})
  set(_deps_football_animation football_foundation)
  set(_deps_football_sim ${_runtime})
  set(_deps_football_ai_contracts ${_base})
  set(_deps_football_ai ${_policy})
  set(_deps_game ${_runtime} ${_policy})
  set(_deps_football_app_support ${_base} football_support)
  set(_deps_football_app game football_app_support ${_runtime} ${_policy})
  set(_deps_football_legacy_anim football_support football_foundation)
  set(_deps_football_anim_baking ${_offline})
  set(_deps_football_anim_baker football_anim_baking ${_offline})

  set(_targets game)
  get_property(_children DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY SUBDIRECTORIES)
  foreach(_child IN LISTS _children)
    file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}" "${_child}")
    if(_relative MATCHES "^src/" OR _relative STREQUAL "tools/animBaker")
      football_directory_targets("${_child}" _nested)
      list(APPEND _targets ${_nested})
    endif()
  endforeach()

  set(_all_files)
  foreach(_target IN LISTS _targets)
    if(NOT DEFINED _root_${_target})
      message(FATAL_ERROR "Module target has no architecture policy: ${_target}")
    endif()
    set(_extra)
    if(_target STREQUAL "game")
      set(_extra FILES gameenv.cpp gameenv.hpp)
    elseif(_target STREQUAL "football_sim")
      set(_extra EXCLUDE_ROOTS "${PROJECT_SOURCE_DIR}/src/sim/animation")
    endif()
    football_validate_target_sources(TARGET ${_target}
      ROOT "${PROJECT_SOURCE_DIR}/src/${_root_${_target}}" ${_extra})
    football_validate_target_dependencies(${_target} ${_deps_${_target}})
    football_owned_files(${_target} _files)
    foreach(_file IN LISTS _files)
      file(REAL_PATH "${PROJECT_SOURCE_DIR}/src/${_file}" _canonical)
      if(_canonical IN_LIST _all_files)
        message(FATAL_ERROR "Duplicate source ownership: ${_file} (${_target})")
      endif()
      list(APPEND _all_files "${_canonical}")
    endforeach()
  endforeach()
endfunction()
