# Architecture comes from actual target properties, including FILE_SET headers.
# Normalize namespaced aliases and static PRIVATE LINK_ONLY edges before traversal.
function(football_direct_links tgt out_var)
  set(_links)
  foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(_values ${tgt} ${_prop})
    if(_values)
      foreach(_value IN LISTS _values)
        string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" _value "${_value}")
        if(_value MATCHES "^\\$<LINK_LIBRARY:[^,]+,(.*)>$")
          string(REPLACE "," ";" _candidates "${CMAKE_MATCH_1}")
        else()
          set(_candidates ${_value})
        endif()
        foreach(_candidate IN LISTS _candidates)
          if(TARGET ${_candidate})
            get_target_property(_canonical ${_candidate} ALIASED_TARGET)
            if(_canonical)
              set(_candidate ${_canonical})
            endif()
            list(APPEND _links ${_candidate})
          elseif(_candidate MATCHES "\\$<")
            message(FATAL_ERROR "Architecture report cannot interpret link edge: ${tgt} -> ${_value}")
          endif()
        endforeach()
      endforeach()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _links)
  set(${out_var} ${_links} PARENT_SCOPE)
endfunction()

function(football_link_closure tgt out_var)
  set(_closure ${tgt})
  set(_queue ${tgt})
  while(_queue)
    list(POP_FRONT _queue _current)
    football_direct_links(${_current} _links)
    foreach(_link IN LISTS _links)
      if(NOT _link IN_LIST _closure)
        list(APPEND _closure ${_link})
        list(APPEND _queue ${_link})
      endif()
    endforeach()
  endwhile()
  set(${out_var} ${_closure} PARENT_SCOPE)
endfunction()

function(football_owned_files tgt out_var)
  get_target_property(_dir ${tgt} SOURCE_DIR)
  set(_files)
  foreach(_prop SOURCES INTERFACE_SOURCES)
    get_target_property(_values ${tgt} ${_prop})
    if(_values)
      list(APPEND _files ${_values})
    endif()
  endforeach()
  foreach(_prop HEADER_SETS INTERFACE_HEADER_SETS)
    get_target_property(_sets ${tgt} ${_prop})
    if(_sets)
      foreach(_set IN LISTS _sets)
        if(_set STREQUAL "HEADERS")
          get_target_property(_headers ${tgt} HEADER_SET)
        else()
          get_target_property(_headers ${tgt} HEADER_SET_${_set})
        endif()
        list(APPEND _files ${_headers})
      endforeach()
    endif()
  endforeach()
  set(_owned)
  foreach(_file IN LISTS _files)
    string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" _file "${_file}")
    if(_file MATCHES "\\$<")
      message(FATAL_ERROR "Architecture report cannot interpret source: ${tgt} -> ${_file}")
    endif()
    get_filename_component(_absolute "${_file}" ABSOLUTE BASE_DIR "${_dir}")
    file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}/src" "${_absolute}")
    list(APPEND _owned ${_relative})
  endforeach()
  list(REMOVE_DUPLICATES _owned)
  set(${out_var} ${_owned} PARENT_SCOPE)
endfunction()

# Discover real module targets, so newly added implementation targets cannot
# silently bypass the report. Alias targets are canonicalized in link traversal.
function(football_directory_targets dir out_var)
  get_property(_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(_children DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
  foreach(_child IN LISTS _children)
    football_directory_targets("${_child}" _nested)
    list(APPEND _targets ${_nested})
  endforeach()
  set(${out_var} ${_targets} PARENT_SCOPE)
endfunction()

set(_module_targets)
get_property(_children DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY SUBDIRECTORIES)
foreach(_child IN LISTS _children)
  file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}" "${_child}")
  if(_relative MATCHES "^src/")
    football_directory_targets("${_child}" _targets)
    list(APPEND _module_targets ${_targets})
  endif()
endforeach()

get_target_property(_contract_headers football_sim_contracts HEADER_SET)
list(TRANSFORM _contract_headers REPLACE "^${PROJECT_SOURCE_DIR}/src/" "")
string(REPLACE ";" " " _contract_headers_text "${_contract_headers}")
set(_report "football_sim_contracts_headers: ${_contract_headers_text}\n")
foreach(_target IN LISTS _module_targets)
  football_link_closure(${_target} _closure)
  string(REPLACE ";" " " _closure_text "${_closure}")
  string(APPEND _report "${_target}: ${_closure_text}\n")
  football_owned_files(${_target} _sources)
  string(REPLACE ";" " " _sources_text "${_sources}")
  string(APPEND _report "${_target}_sources: ${_sources_text}\n")
endforeach()
# Also available to library-only consumers, with no testing/CPM dependency.
file(WRITE "${PROJECT_BINARY_DIR}/module_dependencies.txt" "${_report}")
